### ISSUE TITLE
TestConnAttrs fails

### ISSUE THREAD

**Issue by djshow832** [pingcap/tiproxy#434]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftiproxy%2Fghpr_unit_test/detail/ghpr_unit_test/7/pipeline

### 2. What did you expect to see? (Required)

No error

### 3. What did you see instead (Required)

```
panic: test timed out after 10m0s

running tests:

	TestConnAttrs (9m52s)



goroutine 2546 [running]:

testing.(*M).startAlarm.func1()

	/usr/local/go/src/testing/testing.go:2259 +0x3b9

created by time.goFunc

	/usr/local/go/src/time/sleep.go:176 +0x2d



goroutine 1 [chan receive, 9 minutes]:

testing.(*T).Run(0xc00068b6c0, {0x14bae73?, 0x57f43c?}, 0x1560a50)

	/usr/local/go/src/testing/testing.go:1649 +0x3c8

testing.runTests.func1(0x2817960?)

	/usr/local/go/src/testing/testing.go:2054 +0x3e

testing.tRunner(0xc00068b6c0, 0xc00050bc38)

	/usr/local/go/src/testing/testing.go:1595 +0xff

testing.runTests(0xc000489720?, {0x27cab20, 0x26, 0x26}, {0xd0?, 0xc00050bcf8?, 0x28169a0?})

	/usr/local/go/src/testing/testing.go:2052 +0x445

testing.(*M).Run(0xc000489720)

	/usr/local/go/src/testing/testing.go:1925 +0x636

main.main()

	_testmain.go:155 +0x1bf



goroutine 2509 [semacquire, 9 minutes]:

sync.runtime_Semacquire(0x8b7a73?)

	/usr/local/go/src/runtime/sema.go:62 +0x25

sync.(*WaitGroup).Wait(0xc001002010?)

	/usr/local/go/src/sync/waitgroup.go:116 +0x48

github.com/pingcap/tiproxy/pkg/proxy/backend.(*tcpConnSuite).run(0xc0000401e0, 0xc0004a0060, 0xc00024e400, 0xc0004ab880)

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/pkg/proxy/backend/common_test.go:134 +0x1ef

github.com/pingcap/tiproxy/pkg/proxy/backend.(*testSuite).runAndCheck(0xc00065ffb0, 0x20?, 0x0, 0xc0004a0060, 0xc00024e400, 0x7f6d9a659548?)

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/pkg/proxy/backend/testsuite_test.go:160 +0x57

github.com/pingcap/tiproxy/pkg/proxy/backend.(*backendMgrTester).runTests(0xc00024e2e0, {0xc00014ef00?, 0x4, 0x2?})

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/pkg/proxy/backend/backend_conn_mgr_test.go:252 +0xd2

github.com/pingcap/tiproxy/pkg/proxy/backend.TestConnAttrs(0xc000f824e0)

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/pkg/proxy/backend/backend_conn_mgr_test.go:1101 +0x43c

testing.tRunner(0xc000f824e0, 0x1560a50)

	/usr/local/go/src/testing/testing.go:1595 +0xff

created by testing.(*T).Run in goroutine 1

	/usr/local/go/src/testing/testing.go:1648 +0x3ad



goroutine 2533 [IO wait, 9 minutes]:

internal/poll.runtime_pollWait(0x7f6d9a661e58, 0x72)

	/usr/local/go/src/runtime/netpoll.go:343 +0x85

internal/poll.(*pollDesc).wait(0xc0009a8080?, 0x8aca2b?, 0x0)

	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27

internal/poll.(*pollDesc).waitRead(...)

	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89

internal/poll.(*FD).Accept(0xc0009a8080)

	/usr/local/go/src/internal/poll/fd_unix.go:611 +0x2ac

net.(*netFD).accept(0xc0009a8080)

	/usr/local/go/src/net/fd_unix.go:172 +0x29

net.(*TCPListener).accept(0xc000d82260)

	/usr/local/go/src/net/tcpsock_posix.go:152 +0x1e

net.(*TCPListener).Accept(0xc000d82260)

	/usr/local/go/src/net/tcpsock.go:315 +0x30

github.com/pingcap/tiproxy/pkg/proxy/backend.(*backendMgrTester).handshake4Backend(0xc00024e2e0, 0x20dd660?)

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/pkg/proxy/backend/backend_conn_mgr_test.go:152 +0x2e

github.com/pingcap/tiproxy/pkg/proxy/backend.TestConnAttrs.func2(0xc000f82680?)

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/pkg/proxy/backend/backend_conn_mgr_test.go:1059 +0x38

github.com/pingcap/tiproxy/pkg/proxy/backend.(*tcpConnSuite).run.func2()

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/pkg/proxy/backend/common_test.go:117 +0x30

github.com/pingcap/tiproxy/lib/util/waitgroup.(*WaitGroup).Run.func1()

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/lib/util/waitgroup/waitgroup.go:22 +0x4f

created by github.com/pingcap/tiproxy/lib/util/waitgroup.(*WaitGroup).Run in goroutine 2509

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/lib/util/waitgroup/waitgroup.go:20 +0x73



goroutine 2532 [IO wait, 9 minutes]:

internal/poll.runtime_pollWait(0x7f6d9a661a78, 0x72)

	/usr/local/go/src/runtime/netpoll.go:343 +0x85

internal/poll.(*pollDesc).wait(0xc000818100?, 0xc000a22000?, 0x0)

	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27

internal/poll.(*pollDesc).waitRead(...)

	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89

internal/poll.(*FD).Read(0xc000818100, {0xc000a22000, 0x8000, 0x8000})

	/usr/local/go/src/internal/poll/fd_unix.go:164 +0x27a

net.(*netFD).Read(0xc000818100, {0xc000a22000?, 0x24?, 0xc000ab84e8?})

	/usr/local/go/src/net/fd_posix.go:55 +0x25

net.(*conn).Read(0xc000e3e020, {0xc000a22000?, 0xf?, 0x2814fe0?})

	/usr/local/go/src/net/net.go:179 +0x45

github.com/pingcap/tiproxy/pkg/util/bufio.(*Reader).Read(0xc0004d43c0, {0xc001002004, 0x4, 0x9?})

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/pkg/util/bufio/bufio.go:228 +0x163

github.com/pingcap/tiproxy/pkg/proxy/net.(*basicReadWriter).Read(0xc000b94120, {0xc001002004?, 0x1dc1d28?, 0xc000bf07e0?})

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/pkg/proxy/net/packetio.go:103 +0x2b

github.com/pingcap/tiproxy/pkg/proxy/net.ReadFull({0x170c5c8, 0xc000b94120}, {0xc001002004, 0x4, 0x4})

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/pkg/proxy/net/packetio.go:183 +0x94

github.com/pingcap/tiproxy/pkg/proxy/net.(*PacketIO).readOnePacket(0xc000daa140)

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/pkg/proxy/net/packetio.go:246 +0x36

github.com/pingcap/tiproxy/pkg/proxy/net.(*PacketIO).ReadPacket(0xc000daa140)

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/pkg/proxy/net/packetio.go:264 +0x51

github.com/pingcap/tiproxy/pkg/proxy/backend.(*mockClient).authenticate(0xc0000405a0, 0xc000d07ba0?)

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/pkg/proxy/backend/mock_client_test.go:68 +0x45

github.com/pingcap/tiproxy/pkg/proxy/backend.TestConnAttrs.func1(0xc000d07ba0?)

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/pkg/proxy/backend/backend_conn_mgr_test.go:1055 +0x52

github.com/pingcap/tiproxy/pkg/proxy/backend.(*tcpConnSuite).run.func1()

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/pkg/proxy/backend/common_test.go:109 +0x30

github.com/pingcap/tiproxy/lib/util/waitgroup.(*WaitGroup).Run.func1()

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/lib/util/waitgroup/waitgroup.go:22 +0x4f

created by github.com/pingcap/tiproxy/lib/util/waitgroup.(*WaitGroup).Run in goroutine 2509

	/home/jenkins/agent/workspace/pingcap/tiproxy/ghpr_unit_test/tiproxy/lib/util/waitgroup/waitgroup.go:20 +0x73
```

### 4. What is your version? (Required)

master

**Comment by dveeden** [comment]
Both a `make test` and `cd pkg/proxy/backend/; go test -v -run TestConnAttrs` don't show this error for me locally on Linux x86_64 with main @ 55af11638bfb4ace86ce331fb9c2558b14ea36d8

How do I reproduce this? Or is #435 fixing this ?

**Comment by djshow832** [comment]
> Both a `make test` and `cd pkg/proxy/backend/; go test -v -run TestConnAttrs` don't show this error for me locally on Linux x86_64 with main @ [55af116](https://github.com/pingcap/tiproxy/commit/55af11638bfb4ace86ce331fb9c2558b14ea36d8)
>
> How do I reproduce this? Or is #435 fixing this ?

I can't reproduce it either. It only happened only in CI. Maybe it's because the machine running CI was too slow.

#435 didn't fix this. It only add more logs so that we have a clue when it fails again.

**Comment by djshow832** [comment]
Never happen again, close it.
